//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubezh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rubezh_News
    {
        public int Rubezh_News_id { get; set; }
        public string Rubezh_News_Name { get; set; }
        public string Rubezh_News_Date { get; set; }
        public string Rubezh_News_Text { get; set; }
    }
}
