//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubezh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rubezh_Company
    {
        public int Rubezh_Company_id { get; set; }
        public string Rubezh_Company_Name { get; set; }
    }
}
