//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubezh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rubezh_Main
    {
        public int Rubezh_Main_id { get; set; }
        public Nullable<int> Rubezh_Company_id { get; set; }
        public Nullable<int> Rubezh_Catalog_id { get; set; }
        public Nullable<int> Rubezh_News_id { get; set; }
        public Nullable<int> Rubezh_Price_List_id { get; set; }
    }
}
