//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubezh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rubezh_Price_List
    {
        public int Rubezh_Price_List_id { get; set; }
        public string Rubezh_Price_List_Name { get; set; }
        public byte[] Rubezh_Price_List_File { get; set; }
    }
}
