//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubezh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rubezh_Users
    {
        public int Rubezh_Users_id { get; set; }
        public string Rubezh_Users_Login { get; set; }
        public string Rubezh_Users_Password { get; set; }
        public string Rubezh_Users_Level { get; set; }
    }
}
