//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rubezh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rubezh_Catalog
    {
        public int Rubezh_Catalog_id { get; set; }
        public string Rubezh_Catalog_Name_Company { get; set; }
        public string Rubezh_Catalog_Name { get; set; }
        public byte[] Rubezh_Catalog_Image { get; set; }
        public string Rubezh_Catalog_Description { get; set; }
        public string Rubezh_Catalog_Feature { get; set; }
        public string Rubezh_Catalog_Link { get; set; }
    }
}
